package room

import "errors"

var (
	ErrUserCancelled                      = errors.New("user cancelled envelope")
	ErrRoomDisconnected                   = errors.New("room: disconnected")
	ErrRoomClosed                         = errors.New("room: closed")
	ErrNoConn                             = errors.New("room: no active websocket connection")
	ErrRoomNotFound                       = errors.New("room: not found")
	ErrInvalidPhaseID                     = errors.New("room: invalid phase id")
	ErrInvalidPhaseKey                    = errors.New("room: invalid phase output key")
	ErrInvalidSpreadsheetTableID          = errors.New("room: invalid spreadsheet table id")
	ErrInvalidSpreadsheetColumn           = errors.New("room: invalid spreadsheet column")
	ErrInvalidSpreadsheetRow              = errors.New("room: invalid spreadsheet row")
	ErrInvalidSpreadsheetSavedView        = errors.New("room: invalid spreadsheet saved view")
	ErrInvalidSpreadsheetRowAction        = errors.New("room: invalid spreadsheet row action")
	ErrInvalidSpreadsheetActionID         = errors.New("room: invalid spreadsheet action id")
	ErrInvalidSpreadsheetExportRef        = errors.New("room: invalid spreadsheet export ref")
	ErrInvalidDiffReviewID                = errors.New("room: invalid diff review id")
	ErrInvalidDiffReviewFile              = errors.New("room: invalid diff review file")
	ErrInvalidDiffReviewFilterState       = errors.New("room: invalid diff review filter state")
	ErrInvalidDiffReviewDecision          = errors.New("room: invalid diff review decision")
	ErrInvalidDiffReviewComment           = errors.New("room: invalid diff review comment")
	ErrInvalidDiffReviewArtifactRef       = errors.New("room: invalid diff review artifact ref")
	ErrInvalidApprovalQueueID             = errors.New("room: invalid approval queue id")
	ErrInvalidApprovalQueueItem           = errors.New("room: invalid approval queue item")
	ErrInvalidApprovalQueueDecision       = errors.New("room: invalid approval queue decision")
	ErrInvalidApprovalQueueAuditEntry     = errors.New("room: invalid approval queue audit entry")
	ErrInvalidApprovalQueueExportRef      = errors.New("room: invalid approval queue export ref")
	ErrInvalidWhiteboardBoardID           = errors.New("room: invalid whiteboard board id")
	ErrInvalidWhiteboardSceneSnapshot     = errors.New("room: invalid whiteboard scene snapshot")
	ErrInvalidWhiteboardAssetRef          = errors.New("room: invalid whiteboard asset ref")
	ErrInvalidWhiteboardExportRef         = errors.New("room: invalid whiteboard export ref")
	ErrInvalidWhiteboardRevisionID        = errors.New("room: invalid whiteboard revision id")
	ErrInvalidDraftBlockID                = errors.New("room: invalid draft block id")
	ErrInvalidDraftBlockContent           = errors.New("room: invalid draft block content")
	ErrInvalidFormID                      = errors.New("room: invalid form id")
	ErrInvalidFormSchema                  = errors.New("room: invalid form schema")
	ErrInvalidFormAnswers                 = errors.New("room: invalid form answers")
	ErrInvalidFormSavedDraft              = errors.New("room: invalid form saved draft")
	ErrInvalidFormTemplate                = errors.New("room: invalid form template")
	ErrInvalidFormAction                  = errors.New("room: invalid form action")
	ErrInvalidFormAttachmentRef           = errors.New("room: invalid form attachment ref")
	ErrInvalidProseRevisionID             = errors.New("room: invalid prose revision id")
	ErrInvalidProseRevisionLens           = errors.New("room: invalid prose revision lens")
	ErrInvalidProseRevisionSourceText     = errors.New("room: invalid prose revision source text")
	ErrInvalidProseRevisionSuggestionID   = errors.New("room: invalid prose revision suggestion id")
	ErrInvalidProseRevisionSuggestionText = errors.New("room: invalid prose revision suggestion text")
	ErrInvalidProseRevisionDecision       = errors.New("room: invalid prose revision decision")
	ErrInvalidProseRevisionOutcome        = errors.New("room: invalid prose revision outcome")
	ErrInvalidFinalOutputMarkdown         = errors.New("room: invalid final output markdown")
	ErrInvalidFinalOutputFormat           = errors.New("room: invalid final output format")
)
